### ISSUE TITLE
Issue Building the Application

### ISSUE THREAD

**Issue by frankie-mur** [matheusgomes28/urchin#19] opened 2024-02-15 04:25 UTC
Hey Matheus, cool project! Would love to contribute however I am having an issue running the app using the provided instructions I receive import error.
![image](https://github.com/matheusgomes28/urchin/assets/34355192/c740c764-b415-4cfb-b4ad-670b669d1710)
![image](https://github.com/matheusgomes28/urchin/assets/34355192/01bcb0de-b53b-4d66-a784-f33671af044c)
![image](https://github.com/matheusgomes28/urchin/assets/34355192/056b7e0c-f69a-4ff1-a6d4-fa3d3f2e4700)

Any ideas how to resolve? Thanks!

**Comment by matheusgomes28** [comment] 2024-02-15 18:27
Hey @frankie-mur, sorry for the delay.

What version of Golang are u using? I've tested the build in my machines, and in a random ec2 instance and it seemed to go smooth with Go 1.22.X.

**Comment by matheusgomes28** [comment] 2024-02-15 18:30
random, but could you run `go mod tidy` from the the repo root?

**Comment by frankie-mur** [comment] 2024-02-16 00:15
No worries! Yes I am running `1.22.0` this is the result of `go mod tidy`
<img width="1425" alt="image" src="https://github.com/matheusgomes28/urchin/assets/34355192/778e2bb1-9653-4ed9-9ab2-58b565815651">

**Comment by matheusgomes28** [comment] 2024-02-16 08:23
@frankie-mur Ah, I see the problem. Somehow it should have been `github.com/matheusgomes28/urchin/views`, not `github.com/matheusgomes28/views`... No idea why none of my builds are throwing this error ! Let me try and fix it, thanks for the issue @frankie-mur

**Comment by matheusgomes28** [comment] 2024-02-16 08:55
Right, for the sake of keeping things consistent with the Github repo, I changed the module name in `go.mod` to `github.com/matheusgarcia28/urchin`, but I am unsure if that was the problem. Please pull `main` again !

From the screenshots, it seems like your `go build` and `go mod tidy` are ignoring the information in `go.mod`. Check out the `go.mod` file to see how the module is now defined:

```
module github.com/matheusgomes28/urchin

go 1.22

require (
	github.com/a-h/templ v0.2.543
	github.com/gin-gonic/gin v1.9.1
	github.com/go-sql-driver/mysql v1.7.1
	github.com/gomarkdown/markdown v0.0.0-20231222211730-1d6d20845b47
	github.com/rs/zerolog v1.31.0
	github.com/zutto/shardedmap v0.0.0-20180201164343-415202d0910e
)
```

I.e. the `mod github.com/matheusgomes28/urchin` tells go that any time you import something like `github.com/matheusgomes28/urchin/views`, it should look for the `views` module inside the root directory where the `go.mod` file it. 

This is the output of running `go mod tidy` on a new machine btw. You can see that it finds all the dependencies from github, but **not** the urchin ones. For some reason, your module resolving step is thinking it should be pulling urchin from github, not locally 😄 
``` 
$ go mod tidy
go: downloading github.com/a-h/templ v0.2.543
go: downloading github.com/rs/zerolog v1.31.0
go: downloading github.com/gin-gonic/gin v1.9.1
go: downloading github.com/go-sql-driver/mysql v1.7.1
go: downloading github.com/gomarkdown/markdown v0.0.0-20231222211730-1d6d20845b47
go: downloading github.com/zutto/shardedmap v0.0.0-20180201164343-415202d0910e
go: downloading google.golang.org/protobuf v1.30.0
go: downloading golang.org/x/net v0.17.0
go: downloading github.com/gin-contrib/sse v0.1.0
go: downloading github.com/mattn/go-isatty v0.0.20
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading github.com/pelletier/go-toml/v2 v2.0.8
go: downloading github.com/ugorji/go/codec v1.2.11
go: downloading github.com/bytedance/sonic v1.9.1
go: downloading github.com/goccy/go-json v0.10.2
go: downloading github.com/json-iterator/go v1.1.12
go: downloading github.com/go-playground/validator/v10 v10.14.0
go: downloading github.com/mattn/go-colorable v0.1.13
go: downloading golang.org/x/sys v0.16.0
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/modern-go/reflect2 v1.0.2
go: downloading github.com/gabriel-vasile/mimetype v1.4.2
go: downloading github.com/go-playground/universal-translator v0.18.1
go: downloading github.com/leodido/go-urn v1.2.4
go: downloading golang.org/x/crypto v0.14.0
go: downloading golang.org/x/text v0.13.0
go: downloading github.com/google/gofuzz v1.0.0
go: downloading github.com/stretchr/testify v1.8.3
go: downloading gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405
go: downloading github.com/google/go-cmp v0.6.0
go: downloading github.com/go-playground/assert/v2 v2.2.0
go: downloading github.com/go-playground/locales v0.14.1
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/chenzhuoyu/base64x v0.0.0-20221115062448-fe3a3abad311
go: downloading golang.org/x/arch v0.3.0
go: downloading github.com/twitchyliquid64/golang-asm v0.15.1
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading github.com/klauspost/cpuid/v2 v2.2.4
```

Since I can't reproduce this on my machines, I'd recommend the following: clear your go caches with

```sh
go clean --cache
go clean --modcache
```

Then go into the root dir of `urchin` and run the build with `make build` -- use the Makefile at first to make sure you're building the in exact same way the pipeline is. Let's hope that works, if it doesn't hop on discord and I'll be able to help you !

**Comment by frankie-mur** [comment] 2024-02-16 17:22
Thank for the detailed response @matheusgomes28! This resolved my issue after pulling in the updated changes! Running `make build` I was getting a templ error no such file, this leads me to believe the error may have been due to this as I did not have templ installed on my system. After installing templ everything was smooth. 

I will raise a PR with a suggested resolution to this shortly!

**Comment by matheusgomes28** [comment] 2024-02-16 17:36
@frankie-mur thanks dude! Thank you for the PR and suggestions, I actually have an issue somewhere to upgrade the whole `README.md` ... You will still have issues without `goose` as well btw, that's needed to run the db migrations under `migrations`, I need to add that sections in 😄 

I'll close this for now, but please let me know if you have any more suggestions for improvements.

**Closed by matheusgomes28** 2024-02-16 17:36 UTC
